<?php

require './keypair.php';

/*
SIGN AND VERIFY WITH ASYMMETRIC CRYPTOGRAPHY
 
Your goal is to implement functions to create and verify a digital signature.
 
You have to implement 2 functions. One to create the signature of a given message with a given keypair. Another to verify if the given signature was indeed generated by signing the given message with the given keypair.

$keyPair is an instance of the class KeyPairExample in ./keypair.php. You must complete this class with your code from the previous task.

BONUS: Try not to use any PHP OpenSSL functions, but only the functions provided by the class KeyPairExample.
*/

//Returns the signature of $keyPair on $message.
function sign($message, $keyPair) {
	$hashMsg = $keyPair->getHash($message);
	$finalMsg = $keyPair->encryptWPrivateKey($hashMsg);
	return $finalMsg;
}
 
//Returns true if $signature is the result of signing $message with $keyPair, false otherwise.
function verify($message, $signature, $keyPair) {
	$hashDec = $keyPair->decryptWPublicKey($signature);
	if ($hashDec == $keyPair->getHash($message)) {
		return true;
	} else return false;
}
?>
